### PR TITLE
chore(refactor): update to webpack 4 and make config, smaller

### PR DESCRIPTION
**Pull request by TheLarkInn**
## Overview of changes

* Removed outdated plugins such as ETWP and replaced with MCEP (for webpack 4).
* Created a Development and Production environment
* Separated out the development and production envirionment specific changes into their own configs, then compose these configs at the top level `webpack.config.js` file in root of project (this can be seen as the "common" config). 
* Introudced `webpack-merge` to "object-assign"-like array safe config merges
* Reduced build scripts to `dev` and `prod` scripts. Running their respective environments
* Changed `main.js` to `index.js` to align with webpack's defaults. Now no config is needed for `entry` property.  
* Renamed output directory to `dist` in favor of less configuration
* Updated .gitignore to reflect output directory change
* Preserved original resolution of extensions (instead of overriding defaults)
* Removed `cross-env` and `npm-run-all` because they were not used anymore.

### CODE REVIEW

**Comment by TheLarkInn** [comment]
@Conduitry @Rich-Harris for eyes. I know this has gathered a bit of dust since ya'll got new Rollup out the door so take your time. <3

**Comment by TheLarkInn** [comment]
Ping for sweet love 😘💕💕😘💕😘❤️❤️💕😘😘😘 😘❤️❤️😘❤️😘😘😘😘 😘❤️💕😘💕❤️❤️❤️💕😘💕💕💕❤️❤️❤️💕😘❤️💕😘💕❤️💕😍😘😘❤️😘❤️❤️💕 😘❤️❤️💕 😘😘😘

**Comment by netaisllc** [comment]
Several senators shouted "Merge, merge..."

**Comment by TheLarkInn** [comment]
Not sure how to resolve these particular conflicts. I tried to add favicon to mirror what was on the original template. 

@Conduitry @Rich-Harris ADVISE PRETTY PLEASE TY. 

Also Rich maybe I just have to hunt you down in Barcelona next week 😏

**Comment by benmccann** [comment]
Thanks for this! And sorry it sat awhile. We've just upgraded to Webpack 5, so most of this is out-of-date at this point. Feel free to send a new PR with the remaining changes if you'd like

**Pull request closed without merging**
